import React from 'react';
import ChatItem from './ChatItem';

export default function ChatList() {
  return (
    <div>
      <ChatItem
        name="Alia"
        profileUrl="https://images.pexels.com/photos/11500401/pexels-photo-11500401.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load"
      />
      <ChatItem
        name="Sonam"
        profileUrl="https://images.pexels.com/photos/11523778/pexels-photo-11523778.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load"
      />
      <ChatItem
        name="Aisha"
        profileUrl="https://images.pexels.com/photos/9241604/pexels-photo-9241604.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load"
      />
      <ChatItem
        name="Alia"
        profileUrl="https://images.pexels.com/photos/11500401/pexels-photo-11500401.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load"
      />
      <ChatItem
        name="Sonam"
        profileUrl="https://images.pexels.com/photos/11523778/pexels-photo-11523778.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load"
      />
      <ChatItem
        name="Aisha"
        profileUrl="https://images.pexels.com/photos/9241604/pexels-photo-9241604.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load"
      />
      <ChatItem
        name="Alia"
        profileUrl="https://images.pexels.com/photos/11500401/pexels-photo-11500401.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load"
      />
      <ChatItem
        name="Sonam"
        profileUrl="https://images.pexels.com/photos/11523778/pexels-photo-11523778.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load"
      />
      <ChatItem
        name="Aisha"
        profileUrl="https://images.pexels.com/photos/9241604/pexels-photo-9241604.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load"
      />
      <ChatItem
        name="Alia"
        profileUrl="https://images.pexels.com/photos/11500401/pexels-photo-11500401.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load"
      />
      <ChatItem
        name="Sonam"
        profileUrl="https://images.pexels.com/photos/11523778/pexels-photo-11523778.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load"
      />
      <ChatItem
        name="Aisha"
        profileUrl="https://images.pexels.com/photos/9241604/pexels-photo-9241604.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load"
      />
      <ChatItem
        name="Alia"
        profileUrl="https://images.pexels.com/photos/11500401/pexels-photo-11500401.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load"
      />
      <ChatItem
        name="Sonam"
        profileUrl="https://images.pexels.com/photos/11523778/pexels-photo-11523778.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load"
      />
      <ChatItem
        name="Aisha"
        profileUrl="https://images.pexels.com/photos/9241604/pexels-photo-9241604.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load"
      />
      <ChatItem
        name="Alia"
        profileUrl="https://images.pexels.com/photos/11500401/pexels-photo-11500401.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load"
      />
      <ChatItem
        name="Sonam"
        profileUrl="https://images.pexels.com/photos/11523778/pexels-photo-11523778.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load"
      />
      <ChatItem
        name="Aisha"
        profileUrl="https://images.pexels.com/photos/9241604/pexels-photo-9241604.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load"
      />
    </div>
  );
}
